### ISSUE TITLE
relation to "jsonlines" package

### ISSUE THREAD

**Issue by wbolster** [TeamHG-Memex/json-lines#6]
hi,

are you aware of the [`jsonlines` python library](https://jsonlines.readthedocs.io/) (i am the author), and if so, can you please explain what sets this library apart from it? it seems we're duplicating some functionality...

(i see something about broken gzip handling, but that could maybe be another "layer" instead of weaving it into the json-specific code?)

perhaps it makes more sense to combine efforts instead of wasting effort on the same things. :)

thanks!

**Comment by kmike** [comment]
Hey @wbolster,

I was not aware of jsonlines library when we created this one. It seems your library provides some nice features, like json lines writer. 

Our use case is the following: there could be a .jl.gz file created by a process which appends .jl.gz data to the .jl.gz file created by a previous process, but all these processes can be killed non-gracefully. This is a common case for web scraping tasks. So file may have chunks of both truncated JSON lines and broken gzip data; we want to recover as much information as possible from such files. Recovering from an error condition is what is hard, and gzip/json errors can be hard to separate. For example, if we get a broken JSON line it could either mean a line is truncated, or that it is a gzip decoding problem. Recovering from gzip errors is also harder than it looks, because of how Python implements gzip readers - there are buffers everywhere, so it is hard to get a position in a file we should re-start reading from. The method used in json-lines library makes passing an existing file object impossible if one wants gzip recovery, as we have to create new file objects on-fly, to disable internal buffers.

Initially I tried creating a layer just for gzip recovery (as you suggested), and failed - it was not straightforward, as JSON parsing affects the way you need to recover, and recovering from gzip errors affects JSON lines you're returning. TBH I no longer remember the exact problem, but there is a lot of things which can go wrong if you work with these concatenated half-broken .jl.gz files. That's why gzip+jl is coupled for now. Maybe it is possible to refactor code to decouple it though, such things are easier when there is already a working code. A separate package just for gzip recovery sounds awesome. But it should be done carefully, without breaking existing use cases. I tried to add tests for most errors which were observed in real-world files we wanted to handle, but I'm still not sure they cover it all.

Basic json lines reading code is trivial, it is just a few lines of code. It seems we added different features on top of this, there is almost zero overlap (besides providing a simpler top-level API) - your library is focused on type-based validation of lines, and on proper handling of various file objects passed to reader or writer(?); our library is focused on reading half-broken .jl.gz files.

It could be possible to merge both libraries, but it needs a non-trivial effort, both in writing code (adding jsonlines features to json-lines, or the other way around), and in coordinating of our vision (should we raise an error for lines containing null by default? what about blank lines? should we handle .gz extension automatically? should we use ujson if it is available?). For example, I'd prefer to leave out type validation, as it is opinionated, and there are existing libraries for that (voluptuous, schema, etc.). It seems in the end a merged library could be quite different from both jsonlines and json-lines.

**Comment by wbolster** [comment]
thanks for the elaborate answer. given the intracies of gzip recovery and json parsing, i think both our libraries have a reason to exist. :)

 that said, if you ever need to write `jsonlines`, you now know which library to use. ;)
